### ISSUE TITLE
Add all 6 primary colors for images

### ISSUE THREAD

**Issue by Skyhawk377** [twonirwana/DiscordDiceBot#451]
It would be nice to have image options for _at least_ all 6 of the primary colors with the white numbers, and not just red.

**Comment by twonirwana** [comment]
Yes, that would be nice. It is not complicated to produce the images but some work.
Simply download, install Blender (https://www.blender.org/) and download the 3d dice file (https://github.com/twonirwana/DiscordDiceBot/blob/main/bot/src/blender/d20-red-white.blend).
Then you only need to change the color of the dice and generate images of each side of the dice.
If you or somebody else provides me the png files for the different colors i am happy to include them into the bot.
