### ISSUE TITLE
Rename 5e quickstart options

### ISSUE THREAD

**Issue by Skyhawk377** [twonirwana/DiscordDiceBot#455]
Players are finding them confusing. (Trying to remember which is which.)

What I suggest:

Rename:

a.) "Dungeons & Dragons 5e" to "Dungeons & Dragons 5e - Autoroll dice (without images)"
b.) "Dungeons & Dragons 5e with Dice Images" to "Dungeons & Dragons 5e - Autoroll dice"
c.) "Dungeons & Dragons 5e Calculator" to "Dungeons & Dragons 5e Calculator" (name stays the same)
d.) "Dungeons & Dragons 5e Calculator 2" to "Dungeons & Dragons 5e"

(and then re-order alphabetically)

I think these may be clearer, and may nudge users to try out the autoroll options.

**Comment by twonirwana** [comment]
Thanks for your feedback but this does not reflect my observations. If i look at my log files then i can see that quickstart "Dungeons & Dragons 5e" and "Dungeons & Dragons 5e with Dice Images" are used twice at much as the "Dungeons & Dragons 5e Calculator" and "Dungeons & Dragons 5e Calculator 2". For me the default should have the shortest name, so if i would change something than it would be only "Dungeons & Dragons 5e" to "Dungeons & Dragons 5e (without images)" and "Dungeons & Dragons 5e with Dice Images" to "Dungeons & Dragons 5e".

**Comment by Skyhawk377** [comment]
I have no doubt they are used more. I would imagine not having to press "roll" would be a useful option for beginners and/or non-game masters. 

I just was hoping to add a word (autoroll) to indicate the difference between those 2 and the other 2, merely by looking at the name.

That said, your suggested renames look fine. Though it would be very helpful/clearer if those two were next to each other in the selection list.

As for the 2 calculator ones, the first one has more, different, 5e-related utilities out of all 4 options. And as it has distinct operators, is a calculator.

The second one though, is really just a bunch of dice and +numbers. It's not really a "calculator". It's just based on the "+5" model of 5th ed. Maybe the solution for that is to just call it: "Dungeons & Dragons 5e standard bonuses" - it's a little longer, but clearer.

What do you think?

**Comment by twonirwana** [comment]
Calculator is not perfect but it i like it more than "standard dice bonuses", do you have another idea? I will also try to find a better wording.

**Comment by Skyhawk377** [comment]
I suggested "standard dice bonuses", since the options are "standard dice", and "standard bonuses" per the game.  That said, I'm not sold on it either. Other ideas of course would be great.

A for your suggestion, you could put sum_custom_set in parenthesis:  "Dungeons & Dragons 5e {sum_custom_set}" 

At least that would be clearer and more distinguishable for now, until a better name comes along.
