### ISSUE TITLE
[QUESTION] Is it possible to set the default options of dice configurations at the server level instead of at the individual channel level ?

### ISSUE THREAD

**Issue by p4535992** [twonirwana/DiscordDiceBot#623]
Is it possible to set the default options of dice configurations at the server level instead of at the individual channel level ?

In my use case I would like the “compact ”option to be active for all channels in the server by default.
Is this something that is already possible to do ?

**Comment by twonirwana** [comment]
Sorry, that is currently not possible. But i can put it on the todo list

**Comment by p4535992** [comment]
Ty for the fast response.
